---
"on":
  schedule:
    - cron: "00 1 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: nvim-treesitter/nvim-treesitter
          path: nvim-treesitter
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: |
          scripts/update.sh
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
